name: folio
description: Live portfolio developed in flutter 3.0.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  flip_card: ^0.7.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  file: ^7.0.0

dependency_overrides:
  # conflict carousel_slider: ^4.2.1 and flutter 3.24.0
  # https://github.com/serenader2014/flutter_carousel_slider/issues/454#issuecomment-2272298820
  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/work/
    - assets/photos/
    - assets/services/
    - assets/projects/

    - data.json

  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf
    
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf
    
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
